#!/bin/sh

CHART_DIR=`dirname \`readlink $0\``
INPUT_SEX="$1"
OUTPUT_DOT="$2"

[ -z "$OUTPUT_DOT" ] && OUTPUT_DOT=/tmp/`basename ${INPUT_SEX%.*}`.dot

$CHART_DIR/main.ss $CHART_DIR "$INPUT_SEX" "$OUTPUT_DOT" 

if (false) ; then
    USERDIR=`pwd`
    cd `dirname "$OUTPUT_DOT"`
    xdot "$OUTPUT_DOT" & > /dev/null
    cd $USERDIR
fi
